"""Added delivered field to orders

Revision ID: 293b7424a0a3
Revises: d7a84407ef28
Create Date: 2025-02-12 16:35:24.030614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '293b7424a0a3'
down_revision: Union[str, None] = 'd7a84407ef28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'delivered')
    # ### end Alembic commands ###
