"""Add message_id to Order

Revision ID: 7ffc1b94dedc
Revises: 293b7424a0a3
Create Date: 2025-02-13 16:12:36.506983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ffc1b94dedc'
down_revision: Union[str, None] = '293b7424a0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'message_id')
    # ### end Alembic commands ###
